"""Demo data seeder.

Creates a fully populated demo organization so a new developer (or a sales
demo) has something realistic to look at immediately.

Everything created here is marked ``is_demo = True``, and every scanner result
comes from Zentra's deterministic **mock** providers. The vendor names below are
real, well-known SaaS companies used as realistic examples of a vendor stack —
the security findings attached to them are synthetic fixtures generated by the
mock providers and describe nothing about those companies' actual security
posture. The seeder refuses to run against real providers for exactly that
reason.
"""

from __future__ import annotations

import argparse
import sys
from datetime import UTC, datetime, timedelta
from typing import Any

from sqlalchemy import select

from zentra.config import get_settings
from zentra.core.entitlements import PLANS, Plan
from zentra.db.models import Organization, Scan, Subscription, User
from zentra.db.session import session_scope
from zentra.logging import configure_logging, get_logger
from zentra.services import scans as scans_service
from zentra.services.organizations import create_organization
from zentra.services.vendors import create_vendor

log = get_logger("zentra.seed")

DEMO_EMAIL = "demo@zentra.example"
# Printed by the seeder so a developer can sign in. The seeder refuses to
# run outside a mock-provider, non-production environment.
DEMO_PASSWORD = "Zentra-Demo-2026!"  # noqa: S105 - documented local demo credential
DEMO_ORG = "Northwind Payments (demo)"

#: A realistic UK fintech vendor stack. Scores come from the mock providers.
DEMO_VENDORS: list[dict[str, str]] = [
    {
        "name": "Stripe",
        "domain": "stripe.com",
        "category": "Payments",
        "criticality": "critical",
        "owner_label": "Head of Finance",
        "description": "Card acquiring and payouts. Processes cardholder data on our behalf.",
    },
    {
        "name": "Amazon Web Services",
        "domain": "aws.amazon.com",
        "category": "Infrastructure",
        "criticality": "critical",
        "owner_label": "CTO",
        "description": "Primary cloud hosting provider for all production workloads.",
    },
    {
        "name": "Slack",
        "domain": "slack.com",
        "category": "Collaboration",
        "criticality": "high",
        "owner_label": "Head of Operations",
        "description": "Internal messaging. Contains operational and some customer discussion.",
    },
    {
        "name": "HubSpot",
        "domain": "hubspot.com",
        "category": "CRM & marketing",
        "criticality": "high",
        "owner_label": "Head of Growth",
        "description": "Customer relationship management. Holds prospect and customer contacts.",
    },
    {
        "name": "Notion",
        "domain": "notion.so",
        "category": "Knowledge base",
        "criticality": "medium",
        "owner_label": "Chief of Staff",
        "description": "Internal documentation, including some policy and process material.",
    },
    {
        "name": "Intercom",
        "domain": "intercom.com",
        "category": "Customer support",
        "criticality": "high",
        "owner_label": "Head of Support",
        "description": "Customer support inbox. Holds support conversations and contact details.",
    },
    {
        "name": "Northwind Analytics",
        "domain": "northwind-analytics.example.org",
        "category": "Analytics",
        "criticality": "medium",
        "owner_label": "Data Lead",
        "description": "Fictional analytics supplier used to demonstrate a weaker risk profile.",
    },
    {
        "name": "Cobalt Ledger",
        "domain": "cobalt-ledger.example.net",
        "category": "Accounting",
        "criticality": "high",
        "owner_label": "Financial Controller",
        "description": "Fictional bookkeeping supplier used to demonstrate remediation tracking.",
    },
]


#: Scenario overrides for the two **fictional** vendors only, so the demo shows
#: the full risk range (a high-risk vendor, an at-risk certificate, findings to
#: remediate). Real company domains are deliberately left on whatever the
#: deterministic mock providers produce for them, and never scripted into
#: looking insecure.
FICTIONAL_SCENARIOS: dict[str, dict[str, str]] = {
    "northwind-analytics.example.org": {
        "tls": "expired",
        "dns": "no_dmarc",
        "hibp": "credential_breach",
        "shodan": "database_exposed",
        "tech": "outdated",
        "cve": "critical",
    },
    "cobalt-ledger.example.net": {
        "tls": "expiring",
        "dns": "monitor_only",
        "hibp": "old_breach",
        "shodan": "ssh_exposed",
        "tech": "typical",
        "cve": "medium",
    },
}


def _apply_fictional_scenarios() -> None:
    """Point the mock providers at fixed scenarios for the fictional vendors."""
    from zentra.scanners.cve.provider import MockCveProvider
    from zentra.scanners.dns_sec.provider import MockDnsProvider
    from zentra.scanners.hibp.provider import MockBreachProvider
    from zentra.scanners.shodan.provider import MockExposureProvider
    from zentra.scanners.ssl_labs.provider import MockTlsProvider
    from zentra.scanners.technology.provider import MockTechnologyProvider

    mapping: dict[str, Any] = {
        "tls": MockTlsProvider,
        "dns": MockDnsProvider,
        "hibp": MockBreachProvider,
        "shodan": MockExposureProvider,
        "tech": MockTechnologyProvider,
        "cve": MockCveProvider,
    }
    for domain, scenarios in FICTIONAL_SCENARIOS.items():
        for key, scenario in scenarios.items():
            mapping[key].SCRIPTED[domain] = scenario


def _require_mock_providers() -> None:
    settings = get_settings()
    if not settings.use_mock_scanners:
        raise SystemExit(
            "Refusing to seed with USE_MOCK_SCANNERS=false.\n"
            "The demo dataset must never contain real scan results attributed to real "
            "companies. Set USE_MOCK_SCANNERS=true, or seed a different environment."
        )
    if settings.is_production:
        raise SystemExit("Refusing to seed a production environment.")


def seed(*, reset: bool = False) -> dict[str, str]:
    _require_mock_providers()
    _apply_fictional_scenarios()

    with session_scope() as session:
        existing = session.execute(
            select(Organization).where(Organization.name == DEMO_ORG)
        ).scalar_one_or_none()
        if existing is not None:
            if not reset:
                log.info("seed_already_present", organization_id=str(existing.id))
                return {
                    "organization_id": str(existing.id),
                    "email": DEMO_EMAIL,
                    "status": "already_seeded",
                }
            session.delete(existing)
            session.flush()

        user = session.execute(select(User).where(User.email == DEMO_EMAIL)).scalar_one_or_none()
        if user is None:
            from zentra.core.security import hash_password

            user = User(
                email=DEMO_EMAIL,
                full_name="Demo Operator",
                password_hash=hash_password(DEMO_PASSWORD),
                email_verified_at=datetime.now(UTC),
            )
            session.add(user)
            session.flush()

        organization = create_organization(
            session,
            name=DEMO_ORG,
            owner=user,
            industry="Fintech",
            company_size="10-50",
            country="GB",
            website_domain="northwind-payments.example.com",
        )
        organization.is_demo = True
        organization.plan = Plan.GROWTH.value
        organization.vendor_limit = PLANS[Plan.GROWTH].vendor_limit

        subscription = session.execute(
            select(Subscription).where(Subscription.organization_id == organization.id)
        ).scalar_one()
        subscription.plan = Plan.GROWTH.value
        subscription.status = "active"
        subscription.current_period_end = datetime.now(UTC) + timedelta(days=30)
        session.flush()

        created = 0
        for spec in DEMO_VENDORS:
            vendor = create_vendor(
                session,
                organization=organization,
                name=spec["name"],
                domain=spec["domain"],
                actor=user,
                description=spec["description"],
                category=spec["category"],
                criticality=spec["criticality"],
                owner_label=spec["owner_label"],
                is_demo=True,
            )
            # Run two scans so the demo has a visible score history.
            for index in range(2):
                scan = scans_service.queue_scan(
                    session, vendor=vendor, trigger="initial" if index == 0 else "scheduled"
                )
                scans_service.execute_scan(session, scan.id)
                if index == 0:
                    # Backdate the first scan so the trend chart has two points.
                    stored = session.get(Scan, scan.id)
                    if stored is not None:
                        stored.completed_at = datetime.now(UTC) - timedelta(days=7)
            created += 1

        session.flush()
        log.info(
            "seed_complete",
            organization_id=str(organization.id),
            vendors=created,
        )
        return {
            "organization_id": str(organization.id),
            "email": DEMO_EMAIL,
            "vendors": str(created),
            "status": "seeded",
        }


def main() -> int:
    parser = argparse.ArgumentParser(description="Seed Zentra demo data.")
    parser.add_argument(
        "--reset", action="store_true", help="Delete and recreate the demo organization."
    )
    args = parser.parse_args()

    settings = get_settings()
    configure_logging(settings.log_level, settings.log_format, service="zentra-seed")

    result = seed(reset=args.reset)
    print("\nDemo data ready.")
    print(f"  Organization : {DEMO_ORG}")
    print(f"  Sign in with : {DEMO_EMAIL}")
    print(f"  Password     : {DEMO_PASSWORD}")
    print(f"  Vendors      : {result.get('vendors', 'existing')}")
    print(
        "\nAll scan results in this dataset are synthetic fixtures produced by Zentra's mock\n"
        "providers. They are illustrative only and say nothing about the real security\n"
        "posture of any named company.\n"
    )
    return 0


if __name__ == "__main__":  # pragma: no cover
    sys.exit(main())
